### ISSUE TITLE
Custom logo and favicon not displaying in PeerTube 3.0.1

### ISSUE THREAD

**Issue by DalekDave** [ipbc-dev/peertube-plugin-bittube-logo-favicon#1]
Hello, thank you for your work on this plugin. 

I have had this plugin working in the past on https://tube.tardis.world

Now I've just done a fresh install of Peertube 3.0.1 on a fresh install of Ubuntu 20.04. But now when I install this plugin and specify https://tardis.world/favicon.ico as the favicon and https://tardis.world/peertube-logo.svg as the two images, they don't show up after saving and refreshing the page.

I've tried Chrome and Firefox, and the two images display fine when entered as URLs in a new tab, so they seem to be accessible.

Also, when I enter "bittube" as the parameter in the two fields (without the quote marks), the bittube logo doesn't show up either.

Am I doing something wrong, or is the plugin currently broken?

Is there a hack to get my custom logo and favicon displaying, that you might happen to know about?

With thanks in advance for any tips or help. :-)
And thanks anyway for your original work. ;-)

**Comment by DalekDave** [comment]
Okay, I managed a couple of hacks to get my favicon and logo displaying.

1) Hack for the logo: go to Administration / Configuration / Advanced Configuration / Customizations / CSS of my Peertube instance and paste the following in the custom CSS box:

.icon-logo { 
background-image: url(https://tardis.world/favicon.png) !important;
background-size: 28px 28px !important;
width: 35px !important;
height: 29px !important;
}

That does work, and will survive from upgrade to upgrade, but I'd still prefer to use your plugin instead....

2) Hack for the favicon:  on my server, go to /var/www/peertube/peertube-latest/client/dist/assets/images and paste in my desired favicon ( favicon.png ). Then enter the following path in the favicon field of your plugin;

/client/assets/images/favicon.png

I guess that would also work for the logo, too. But it won't survive from upgrade to upgrade, and I would still prefer to use your plugin and an external image (located on another domain, for instance).

Anyway, maybe that will help someone else looking for a temporary solution to the same problem... ;-)

**Comment by ipbc-dev** [comment]
Hi! I have done several tests and it always works for me. I've even borrowed your urls and your icons appear perfectly to me. The example code that you propose is practically the same as the plugin does. It's so simple that I don't know what might be failing so that it doesn't work for you, but I'm going to close the issue as it doesn't seem to be consistent. Sorry for the delay, I tested this a long time ago but I was distracted from answering you. Apologies
